# Generated by Django 4.2.7 on 2024-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incidentticket_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
