# Generated by Django 4.2.7 on 2024-11-18 15:50

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_reactiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontime',
            name='user',
            field=models.ForeignKey('auth.User', on_delete=models.CASCADE),
        ),
    ]
