# Generated by Django 4.2.7 on 2024-11-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241118_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='sprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.CharField(max_length=200),
        ),
    ]
