# Generated by Django 4.2.7 on 2024-09-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verdict_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verdict',
        ),
    ]
